### ISSUE TITLE
Re-organize ACS distribution

### ISSUE THREAD

**Issue by jhschwarz** [ACS-Community/ACS#1]
The straight checkout of ACS from svn is about 3.3 GB when the .svn directory is excluded. As a first cut, the ExtProd directory tree (2.5 GB, still too large according to the GitHub recommendation) could be made into a separate repository and the Web directory tree either deleted or also made into a separate repository. The rest of the distribution, which is mostly LGPL and the one most likely to change frequently, amounts to about 500 MB, which is quite reasonable.

To really optimize this properly, though, the files in ExtProd should be replaced by links to their original repository locations.

And then, we need to provide instructions and/or a build script to do the whole thing.

**Comment by javarias** [comment]
I think this ticket is complete. If further reorganization is needed, then we should open new ticket with specific tasks. For now the repository is organized well enough to be handled in github.
