### ISSUE TITLE
Port ACS to Ubuntu

### ISSUE THREAD

**Issue by javarias** [ACS-Community/ACS#10]
As an alternative for some users, it is necessary to port ACS to Ubuntu.

The current Ubuntu version is 14.04 LTS. ubuntu distribution has a newer set of gcc compilers (gcc 4.8.x), which a stricter than the gcc available in RHEL 6.5

**Comment by javarias** [comment]
I tried to replicate the problem that @normansaez  and @pdevicente reported, but I was unable to replicate the failing acsStart. I just did a fresh installation of Ubuntu 14.04.1 in a Vmware VMm installing on top the needed packages to run ACS.

If any of you could give a VM (it doesn't matter the VM software) on which the problem can be replicated, it would be great!

**Comment by normansaez** [comment]
@javarias I have a VM with the problem mentioned here. It was build with vmware. Write me how provide it to you.

**Comment by tzuchiangshen** [comment]
it worked for me! Thank you Bogdan. 
===
try to modify/remove "SourceThread" from:
$ACSROOT/config/svc.conf/defaultNotify.svc.conf

**Comment by normansaez** [comment]
Hi Tzu!

So you just commented out the line indicated by Bogdan and it worked? 
or you change the configuration a little bit ?

**Comment by jantogni** [comment]
Hi, I created the machine that Tzu was using. 

Initially I created 8gb virtual machine with centos 6.7. After moving the virtual machine to 1gb, this problem appear. With 2gb the problem persist. But with 4gb the problem didn't appear.

**Comment by javarias** [comment]
The changes to support Ubuntu were merge with pull request #53 
I am closing this ticket given the pull request as been accepted
