### ISSUE TITLE
Create public binary repository for community build products

### ISSUE THREAD

**Issue by moraklein** [ACS-Community/ACS#25]
Provide a public binary repository with the community build products (#4) in tarball format. This repository must be accessible at least via web (navigation-friendly for users) and rsync (for replication to external mirrors).
A list of binary repositories should be maintained [here](https://github.com/ACS-Community/ACS/wiki/Official%20Binaries).

**Comment by guigue** [comment]
We implemented a periodic  rsync copy of the UFSM binary repository.  The link to our repository: http://www.llamaobservatory.org/~acs-mirror/build/

**Comment by javarias** [comment]
The public repository is completed, the master server is available at: http://lc-ip92.inf.utfsm.cl/userContent/
We have a mirror at: http://www.llamaobservatory.org/~acs-mirror/build/
And also the public anonymous rsync is provided at: rsync://lc-ip92.inf.utfsm.cl/builds
