### ISSUE TITLE
Distributed Build-Farm design and architecture

### ISSUE THREAD

**Issue by moraklein** [ACS-Community/ACS#36]
Design and implement a distributed build-farm architecture for the ACS community repository, based on the experience from #4 and #25. The goal is to deploy this system in multiple locations and servers to provide periodic ACS builds on all supported platforms and OS versions. The proposed solution must be aligned with the requirements and needs of the community, and be made publicly available.

Details of this project are being followed up here:
https://ictwiki.alma.cl/twiki/bin/view/Main/BuildFarmACSCommunity

Please report general status updates and milestones on this issue ticket.

**Comment by atejeda** [comment]
This can help, take a look to https://github.com/ACS-Community/ACS/issues/34

For the building system:
https://github.com/atejeda/almasw-modbuilder-plugin
https://github.com/atejeda/almasw-modbuilder-plugin/wiki

hope that helps.

**Comment by jbarriosc** [comment]
Hi, sorry for being so far from this in github. I have been worked in this issue a few months ago and I have done a architecture proposal in order #4 and #25, and aligned to the requirements of the community. Now i have to end the developing and testing of this architecture in order to answer #36.

**Comment by jbarriosc** [comment]
Hi, i have been working in a system of servers using jenkins like main server and apache server to do a system able to execute automated distributed tasks to install and test ACS in Ubuntu 14.04 LTS 64bits and Centos 6.6 32/64 bits proving different versions of ACS, generating reports and binaries tested from the installation:  
ACS-$BRANCH-$DATE-$COMMIT-$LINUX_RELEASE.tar.bz2 to ACS software ExtProds-$BRANCH-$DATE-$COMMIT-$LINUX_RELEASE.tar.bz2 to external tools, build-$BRANCH-$DATE-$COMMIT-$LINUX_RELEASE.log to install log and test-$BRANCH-$DATE-$COMMIT-$LINUX_RELEASE.log to test log.
This files are available temporarily in this first web version. 
http://www.cmcc.ufro.cl/alma/
Current versions of CentOS 32-bit and 64-bit Ubuntu 14.04 are not passing the tests, and the 64-bit CentOS testing goes well.

The system is automated to do nightly builds at 10 pm (UTC-3h), the folders are recycled every thirty days in the main server and mirror server.

**Comment by atejeda** [comment]
A few questions:
* there's any strong reason to build external products if there's no change between the builds?
* there's any strong reason to build the whole software if there's no changes between builds?, e.g.: builds triggered by a sccm hook
* by reports you mean test logs, right?

Suggestions:
* would be nice to have a md5 checksum
* a symlink pointing to the latest build

**Comment by jantogni** [comment]
@jbarriosc designed the architecture of the build farm, and also implemented a prototype of the architecture. 

Since the idea of this ticket is done, I will close this ticket.
