### ISSUE TITLE
ACS-OCT2017 on Centos7

### ISSUE THREAD

**Issue by cvalenzu** [ACS-Community/ACS#55]
Hello Everyone,

With @LeoXDXp merged the community branch with the ALMA public git repository in https://github.com/csrg-utfsm/acscb/tree/merges and we compiled it on centos 7 in https://jenkins.csrg.cl/view/ACS-Community/job/ACS-Community/job/Merges/

You can check our branch if you want to merge it with the community.

**Comment by javarias** [comment]
Could you create a pull request to evaluate if it posible to merge your changes into this repository?

**Comment by cvalenzu** [comment]
Ok, we will try to do it this week or next week.

Im going to close this issue, we discuss furthermore in the pull request itself.

**Comment by DirkHoffmann** [comment]
Any news on this? Could you point me to the MR or link it here?

**Comment by cvalenzu** [comment]
Sorry for the delay, we made the pull request today #56
