### ISSUE TITLE
Standardization of documentation format

### ISSUE THREAD

**Issue by atejeda** [ACS-Community/ACS#8]
What I propose is to "migrate" all the current documentation to a same format, in this case as a markdown syntax which is readable by Github, this can be archived in a different repo e.g.: ACS/Documentation and added as a submodule or, migrated to Wiki Github pages. If is feasible, on top of this, review it (specially the tutorials).

**Comment by jantogni** [comment]
@javarias decided that the future documentation will be written in reStructuredText, and will be placed at ACS/Documentation. 

To migrate the current documentation (ACS/Documentation) to reStructuredText will be not part of the millestione 1 nor 2.
